spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/campusgig
spring.datasource.username=postgres
spring.datasource.password=7880
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.secret=CampusGigSecretKeyThatIsAtLeast256BitsLongForHS384SignatureAlgorithmSecurity
file.upload-dir=uploads
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-exceptions=false
spring.mvc.throw-exception-if-no-handler-found=true
